sudo: false
language: node_js
cache:
  directories:
  - "~/.yarn"
  - "~/.nvm"
node_js:
  - 'stable'
before_install:
- npm install -g yarn
install:
- yarn
script:
- npm run lint
- npm test
- make build
after_success:
- cd build
- git init
- git config user.name "Travis CI"
- git config user.email "travis@coderbyheart.com"
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
