sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
services:
  - redis-server
node_js:
  - 'stable'
before_install:
- npm install -g yarn
install:
- yarn
script:
  - npm run lint
  - npm run test:coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
