sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
services:
  - redis-server
node_js:
  - 'stable'
before_install:
- npm install -g yarn
install:
- yarn
script:
- npm run lint
- npm test
- make build
after_success:
- cd build
- git init
- git config user.name "Travis CI"
- git config user.email "travis@coderbyheart.com"
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
